app:
  log:
    level: "INFO" # "DEBUG", "INFO", "WARN" or "ERROR"
    log_format: "text" # "text" or "json"
    log2console: true
    log2file: true
    file_path: "./application.log"
    file_mode: "rotate" # "overwrite", "append" or "rotate"
    old_logs_folder: "logs/"
  api:
    gin_release_mode: true
    host: "0.0.0.0" # "127.0.0.1" or "0.0.0.0" (listen on all interfaces)
    port: 8080
    base_path: "/api/v1"
    shutdown_timeout: "5s"
    auth:
      jwt_issuer: "your-app-name"
      jwt_audience: "your-domain.com"
      access_token_secret: "your-super-secret-access-key" # use `openssl rand -hex 32`
      refresh_token_secret: "your-super-secret-refresh-key" # use `openssl rand -hex 32`
      access_token_ttl: "24h"
      refresh_token_ttl: "168h" # 7 days
      pwd_reset_token_ttl: "1h"
      email_verify_token_ttl: "24h"
  webapp:
    domain: "wishlist.itskoshkin.ru"
  database:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "4221"
    database_name: "wishlist"
    ssl_mode: "disable"
  redis:
    host: "localhost"
    port: 6379
    password: "4221"
    database: 0
  minio:
    endpoint: "localhost:9000"
    access_key_id: "Q3AM..."
    access_key_secret: "zf+t..."
    use_ssl: false
    bucket_name: "wishlist"
    max_upload_size_mb: 10
  email:
    host: "smtp.gmail.com"
    port: "587"
    user: "your@gmail.com" # Address with +tag (your+wishlist@gmail.com) can also be used, but first add it at https://mail.google.com/mail/u/0/#settings/accounts in section "Send mail as"
    password: "4221" # Google app password from https://myaccount.google.com/apppasswords, see https://support.google.com/mail/answer/185833?hl=en for more info
    from: "Wishlist <your@gmail.com>"
  broker:
    type: "none" # "none", "kafka" or "rabbitmq"
    kafka:
      brokers:
        - "localhost:9092"
      group_id: "wishlist-worker"
      topic_prefix: "wishlist"
      auth:
        enabled: false
        mechanism: "plain"
        username: "wishlist"
        password: "password"
        tls: false
    rabbitmq:
      url: "amqp://username:password@localhost:5672/"
